/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "from-TyGrass",
    "from-TyFire",
    "from-TyWater",
    "from-TyElectric",
    "from-TyBug",
    "from-TyNormal",
    "from-TyPoison",
    "from-TyFairy",
    "from-TyFighting",
    "from-TyPsychic",
    "from-TyRock",
    "from-TyGhost",
    "from-TyIce",
    "from-TyDragon",
    "from-TyGround",
    "from-TyFlying",
    "from-TySteel",
    "from-Black",
    "from-White",
    "from-Red",
    "from-DarkGrey",
    "from-LigthGrey",

    "bg-TyGrass",
    "bg-TyFire",
    "bg-TyWater",
    "bg-TyElectric",
    "bg-TyBug",
    "bg-TyNormal",
    "bg-TyPoison",
    "bg-TyFairy",
    "bg-TyFighting",
    "bg-TyPsychic",
    "bg-TyRock",
    "bg-TyGhost",
    "bg-TyIce",
    "bg-TyDragon",
    "bg-TyGround",
    "bg-TyFlying",
    "bg-TySteel",
    "bg-Black",
    "bg-White",
    "bg-Red",
    "bg-DarkGrey",
    "bg-LigthGrey",
  ],
  theme: {
    extend: {
      screens: {
        mini: "250px",
        sm: "480px",
        md: "600px",
      },
    },
    minWidth: {
      220: "13.75rem",
      fit: "fit-content",
    },
    maxHeight: { fullScreen: "calc(100vh - 6.25rem )" },
    width: {
      28: "1.75rem",
      36: "2.25rem",
      70: "4.375rem",
      154: "9.625rem",
      250: "15.625rem",
      full: "100%",
    },
    padding: {
      50: "3.125rem",
      40: "2.5rem",
      20: "1.25rem",
      15: "0.9375rem",
      14: "0.875rem",
      10: "0.625rem",
      8: "0.5rem",
      5: "0.3125rem",
      4: "0.25rem",
      0: "0px",
    },
    gap: {
      25: "1.5625rem",
      20: "1.25rem",
      10: "0.625rem",
      8: "0.5rem",
      7: "0.4375rem",
      6: "0.375rem",
      4: "0.25rem",
    },
    colors: {
      Black: "#000000",
      White: "#FFFFFF",
      Red: "#FF4444",
      DarkGrey: "#D5D5D5",
      LigthGrey: "#E2E2E2",
      TyBug: "#91C12F",
      TyDark: "#5A5465",
      TyDragon: "#0B6DC3",
      TyElectric: "#F4D23C",
      TyFairy: "#EC8FE6",
      TyFighting: "#CE416B",
      TyFire: "#FF9D55",
      TyFlying: "#89AAE3",
      TyGhost: "#5269AD",
      TyGround: "#D97845",
      TyIce: "#73CEC0",
      TyPoison: "#B567CE",
      TyRock: "#C5B78C",
      TyWater: "#5090D6",
      TySteel: "#5A8EA2",
      TyGrass: "#63BC5A",
      TyPsychic: "#FA7179",
      TyNormal: "#919AA2",
      Detective: "#feb81c",
    },
    fontFamily: {
      main: "Helvetica, non-serif",
    },
    fontSize: {
      32: "2rem",
      18: "1.125rem",
      14: "0.875rem",
      12: "0.75rem",
    },
  },
  plugins: [],
};
